[package]
name = "trit"
version = "0.1.3"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>"]
description = "Trinary crate"
license = "MIT"
repository = "https://github.com/lachlansneff/trit"

[dependencies]
